on: [push]

jobs:
  dorametrix:
    runs-on: ubuntu-latest
    name: Dorametrix
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dorametrix
        uses: mikaelvesavuori/dorametrix-action@v1.0.0
        with:
          endpoint: "https://djn6bu56k2.execute-api.us-west-2.amazonaws.com"
          api-key: '82490d5a-1950-4527-ab2f-5c984c861462'
